### ISSUE TITLE
wrong repository url

### ISSUE THREAD

**Issue by joseluis** [RustyYato/pui#1]
It points to another project, as seen in: https://docs.rs/crate/pui/0.4.1/source/Cargo.toml

It should point to: https://github.com/RustyYato/pui

**Comment by RustyYato** [comment]
Yep, I'm currently overhauling `pui`, so things are a bit out of sync. I can't change the old docs, but the new version will be available in the next few days. If you want to see the previous repository, it had been renamed to https://github.com/RustyYato/pui-old

**Comment by RustyYato** [comment]
Oh, wait I see what you're talking about! Thanks for the issue, this should be fixed in the overhaul.
